### ISSUE TITLE
Compare with cppRouting

### ISSUE THREAD

**Issue by Robinlovelace** [UrbanAnalyst/uta-engine#16]
Hi Mark, just happened across this and sounds amazing! I've just been playing with `cppRouting` and wondered it would be worth comparing with it in addition to comparisons with valhalla and r5.

**Comment by mpadge** [comment]
Hey Robin, great that you're interested. The benchmarks at the moment are about accuracy, and specifically to support the need for these, quite complex algorithms to generate actual, realistic travel time estimates. But they coulld easily be extended to efficiency comparison too, I suppose. I don't like efficiency comparisons, because they are never fair, but that doesnt stop anyone else, so i guess why not?

**Comment by Robinlovelace** [comment]
Could be worth testing accuracy also. I had a look at the benchmarks vignette and think it could be worth adding a line for `cppRouting` for comparison https://github.com/UrbanAnalyst/ua-engine/blob/main/vignettes/benchmarks.Rmd#L89

Regarding accuracy, what's the ground truth data of travel times used so far? I know of a few datasets with flow on the network but not accurate travel times for specific trips.

**Comment by mpadge** [comment]
See [this comment](https://github.com/UrbanAnalyst/dodgr/issues/212#issuecomment-1617697837) on the difficulty of benchmarking against `cppRouting`. The travel times calibration procedures are documented in https://github.com/UrbanAnalyst/ttcalib, using the aggregated data from [Uber Movement](https://movement.uber.com/). Those parameters all end up defining waiting times at traffic lights, and waiting times to turn against oncoming traffic. Both of those are critical parameters that determine the final results here, and which `cppRouting` can in no way capture, so there can be no direct comparison here. Valhalla and R5 at least capture effects like that, and so comparison is more fair with those.

**Comment by Robinlovelace** [comment]
Sounds good and makes sense so closing for now...
